/* tslint:disable */
/* eslint-disable */
/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/prompt-values-api';
export * from './api/job-changes-api';
export * from './api/job-families-api';
export * from './api/job-profiles-api';
export * from './api/jobs-api';
export * from './api/organization-assignment-changes-api';
export * from './api/supervisory-organizations-api';
export * from './api/workers-api';

