/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  PromptValuesApi,
  JobChangesApi,
  JobFamiliesApi,
  JobProfilesApi,
  JobsApi,
  OrganizationAssignmentChangesApi,
  SupervisoryOrganizationsApi,
  WorkersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { WorkdayStaffingCustom } from "./client-custom";

export class WorkdayStaffing extends WorkdayStaffingCustom {
  readonly promptValues: PromptValuesApi;
  readonly jobChanges: JobChangesApi;
  readonly jobFamilies: JobFamiliesApi;
  readonly jobProfiles: JobProfilesApi;
  readonly jobs: JobsApi;
  readonly organizationAssignmentChanges: OrganizationAssignmentChangesApi;
  readonly supervisoryOrganizations: SupervisoryOrganizationsApi;
  readonly workers: WorkersApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.promptValues = new PromptValuesApi(configuration);
    this.jobChanges = new JobChangesApi(configuration);
    this.jobFamilies = new JobFamiliesApi(configuration);
    this.jobProfiles = new JobProfilesApi(configuration);
    this.jobs = new JobsApi(configuration);
    this.organizationAssignmentChanges = new OrganizationAssignmentChangesApi(configuration);
    this.supervisoryOrganizations = new SupervisoryOrganizationsApi(configuration);
    this.workers = new WorkersApi(configuration);
  }

}
