/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * For a past or current business process, the value of the Assignment Type field that is being (or was) proposed in the process.
 * @export
 * @interface AssignmentType23929e1f68ca10000d6940d6bde56963
 */
export interface AssignmentType23929e1f68ca10000d6940d6bde56963 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof AssignmentType23929e1f68ca10000d6940d6bde56963
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof AssignmentType23929e1f68ca10000d6940d6bde56963
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof AssignmentType23929e1f68ca10000d6940d6bde56963
     */
    'href'?: string;
}

