/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902eaAllOf } from './associated-check-in-topic-detail316b5a26cc3c100010a01184c23902ea-all-of';

/**
 * 
 * @export
 * @interface AssociatedCheckInDetail3267c0ba92a0100016ed105476ad03c4
 */
export interface AssociatedCheckInDetail3267c0ba92a0100016ed105476ad03c4 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof AssociatedCheckInDetail3267c0ba92a0100016ed105476ad03c4
     */
    'id'?: string;
}

