/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020AllOf
 */
export interface AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020AllOf {
    /**
     * Indicates that the check-in is archived.
     * @type {boolean}
     * @memberof AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020AllOf
     */
    'archived'?: boolean;
    /**
     * Date of check-in.
     * @type {string}
     * @memberof AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020AllOf
     */
    'date'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020AllOf
     */
    'id'?: string;
}

