/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns the category of a Business Process Attachment.
 * @export
 * @interface Category43b30ba735b8100011ee4781a9d50146
 */
export interface Category43b30ba735b8100011ee4781a9d50146 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Category43b30ba735b8100011ee4781a9d50146
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Category43b30ba735b8100011ee4781a9d50146
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Category43b30ba735b8100011ee4781a9d50146
     */
    'href'?: string;
}

