/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HeadcountOption97af9049a5fd10001c48896fbde30000 } from './headcount-option97af9049a5fd10001c48896fbde30000';

/**
 * 
 * @export
 * @interface ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
 */
export interface ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf {
    /**
     * 
     * @type {HeadcountOption97af9049a5fd10001c48896fbde30000}
     * @memberof ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
     */
    'headcountOption'?: HeadcountOption97af9049a5fd10001c48896fbde30000;
    /**
     * Returns true if the value for \'Available for job overlap\' box is checked
     * @type {boolean}
     * @memberof ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
     */
    'openingAvailableForOverlap'?: boolean;
    /**
     * Id of the instance
     * @type {string}
     * @memberof ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ChangeJobOpeningData97af9049a5fd10001c4888d654170000AllOf
     */
    'descriptor'?: string;
}

