/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeOrganizationAssignmentDefaultRepresentationDb2f38bfb555100012de1eb17c2f00ffAllOf } from './change-organization-assignment-default-representation-db2f38bfb555100012de1eb17c2f00ff-all-of';

/**
 * 
 * @export
 * @interface ChangeOrganizationAssignmentDefaultRepresentationDb2f38bfb555100012de1eb17c2f00ff
 */
export interface ChangeOrganizationAssignmentDefaultRepresentationDb2f38bfb555100012de1eb17c2f00ff {
    /**
     * Id of the instance
     * @type {string}
     * @memberof ChangeOrganizationAssignmentDefaultRepresentationDb2f38bfb555100012de1eb17c2f00ff
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ChangeOrganizationAssignmentDefaultRepresentationDb2f38bfb555100012de1eb17c2f00ff
     */
    'descriptor'?: string;
}

