/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobBusinessTitle3db8095ffa18100013a5f96969ca0102AllOf } from './change-job-business-title3db8095ffa18100013a5f96969ca0102-all-of';

/**
 * 
 * @export
 * @interface ChangeJobBusinessTitle3db8095ffa18100013a5f96969ca0102
 */
export interface ChangeJobBusinessTitle3db8095ffa18100013a5f96969ca0102 {
    /**
     * The new business title for the worker as of the effective date.  If there is no business title override, this field defaults to the job title or job profile name.
     * @type {string}
     * @memberof ChangeJobBusinessTitle3db8095ffa18100013a5f96969ca0102
     */
    'businessTitle'?: string;
}

