/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137AllOf } from './change-job-company-insider-types-data05d4c45042b61000131e4b2132f30137-all-of';

/**
 * 
 * @export
 * @interface ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137
 */
export interface ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137
     */
    'descriptor'?: string;
}

