/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssignmentType23929e1f68ca10000d6940d6bde56963 } from './assignment-type23929e1f68ca10000d6940d6bde56963';
import { ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137 } from './change-job-company-insider-types-data05d4c45042b61000131e4b2132f30137';
import { PayRateTypeD25283821c01100016756a14eb650000 } from './pay-rate-type-d25283821c01100016756a14eb650000';
import { PositionWorkerType05d4c45042b610001030ee47f2c90118 } from './position-worker-type05d4c45042b610001030ee47f2c90118';
import { TimeType05d4c45042b610000bb540b7458e0108 } from './time-type05d4c45042b610000bb540b7458e0108';
import { WorkStudy05d4c45042b610000ba2f83c70f30101 } from './work-study05d4c45042b610000ba2f83c70f30101';
import { WorkersCompensationCodeOverride05d4c45042b61000138500e185e0013f } from './workers-compensation-code-override05d4c45042b61000138500e185e0013f';

/**
 * 
 * @export
 * @interface ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
 */
export interface ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf {
    /**
     * 
     * @type {PayRateTypeD25283821c01100016756a14eb650000}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'payRateType'?: PayRateTypeD25283821c01100016756a14eb650000;
    /**
     * 
     * @type {WorkersCompensationCodeOverride05d4c45042b61000138500e185e0013f}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'workersCompensationCodeOverride'?: WorkersCompensationCodeOverride05d4c45042b61000138500e185e0013f;
    /**
     * Full Time Equivalent for a worker calculated by scheduled weekly hours divided by default weekly hours either current or proposed.
     * @type {number}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'fte'?: number;
    /**
     * Returns the date that the employee should be notified for a termination.
     * @type {string}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'notifyBy'?: string;
    /**
     * The new company insider types for the worker as of the effective date.
     * @type {Array<ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137>}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'companyInsiderTypes'?: Array<ChangeJobCompanyInsiderTypesData05d4c45042b61000131e4b2132f30137>;
    /**
     * The first day of work for the worker, as specified on the Hire, Add International Assignment, or Add Job transaction. This field will not return a value for any other transaction.
     * @type {string}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'firstDayOfWork'?: string;
    /**
     * The new default weekly hours for the worker as of the effective date.
     * @type {number}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'defaultWeeklyHours'?: number;
    /**
     * 
     * @type {PositionWorkerType05d4c45042b610001030ee47f2c90118}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'positionWorkerType'?: PositionWorkerType05d4c45042b610001030ee47f2c90118;
    /**
     * The working full time equivalent for the worker as of the effective date.
     * @type {number}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'workingFte'?: number;
    /**
     * True if working full time equivalent is specified on a worker as of the effective date.
     * @type {boolean}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'specifyWorkingFte'?: boolean;
    /**
     * 
     * @type {TimeType05d4c45042b610000bb540b7458e0108}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'timeType'?: TimeType05d4c45042b610000bb540b7458e0108;
    /**
     * True if paid full time equivalent is specified on a worker as of the effective date.
     * @type {boolean}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'specifyPaidFte'?: boolean;
    /**
     * The paid full time equivalent for the worker as of the effective date.
     * @type {number}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'paidFte'?: number;
    /**
     * 
     * @type {WorkStudy05d4c45042b610000ba2f83c70f30101}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'workStudy'?: WorkStudy05d4c45042b610000ba2f83c70f30101;
    /**
     * 
     * @type {AssignmentType23929e1f68ca10000d6940d6bde56963}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'assignmentType'?: AssignmentType23929e1f68ca10000d6940d6bde56963;
    /**
     * The new End Employment Date for the worker. If the worker has an Employee Contract sub event, this field will return that end date instead.
     * @type {string}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'endEmploymentDate'?: string;
    /**
     * For a past or current business process, the value of the Expected Assignment End Date field that is being (or was) proposed in the process.
     * @type {string}
     * @memberof ChangeJobAdministrativeDetailsDataF8f20079bc5a1000089ccb7f6a8800eaAllOf
     */
    'expectedAssignmentEndDate'?: string;
}

