/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221AllOf } from './change-job-position-data-dfc4e58f7308100018bd1c459f435221-all-of';
import { JobRequisitionDfc4e58f730810001ad60325d9bc52cf } from './job-requisition-dfc4e58f730810001ad60325d9bc52cf';
import { PositionDfc4e58f730810001ad60369c23452d1 } from './position-dfc4e58f730810001ad60369c23452d1';

/**
 * 
 * @export
 * @interface ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
 */
export interface ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221 {
    /**
     * Returns true if the position is being created.
     * @type {boolean}
     * @memberof ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    'createPosition'?: boolean;
    /**
     * Returns true if the value for \'Available for job overlap\' box is checked
     * @type {boolean}
     * @memberof ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    'availableForOverlap'?: boolean;
    /**
     * 
     * @type {PositionDfc4e58f730810001ad60369c23452d1}
     * @memberof ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    'position'?: PositionDfc4e58f730810001ad60369c23452d1;
    /**
     * Returns true if the position is being closed.
     * @type {boolean}
     * @memberof ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    'closePosition'?: boolean;
    /**
     * 
     * @type {JobRequisitionDfc4e58f730810001ad60325d9bc52cf}
     * @memberof ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    'jobRequisition'?: JobRequisitionDfc4e58f730810001ad60325d9bc52cf;
    /**
     * Id of the instance
     * @type {string}
     * @memberof ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221
     */
    'descriptor'?: string;
}

