/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobDefaultRepresentation6cc31ee444d010000bb4153a954300e7AllOf } from './change-job-default-representation6cc31ee444d010000bb4153a954300e7-all-of';

/**
 * 
 * @export
 * @interface ChangeJobDefaultRepresentation6cc31ee444d010000bb4153a954300e7
 */
export interface ChangeJobDefaultRepresentation6cc31ee444d010000bb4153a954300e7 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof ChangeJobDefaultRepresentation6cc31ee444d010000bb4153a954300e7
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ChangeJobDefaultRepresentation6cc31ee444d010000bb4153a954300e7
     */
    'descriptor'?: string;
}

