/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115AllOf } from './change-job-job-profile-data3db8095ffa18100013f019a27a1f0115-all-of';
import { JobProfile3db8095ffa18100013f019afc6d30116 } from './job-profile3db8095ffa18100013f019afc6d30116';

/**
 * 
 * @export
 * @interface ChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115
 */
export interface ChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115 {
    /**
     * 
     * @type {JobProfile3db8095ffa18100013f019afc6d30116}
     * @memberof ChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115
     */
    'jobProfile'?: JobProfile3db8095ffa18100013f019afc6d30116;
    /**
     * The new job title for the worker as of the effective date.
     * @type {string}
     * @memberof ChangeJobJobProfileData3db8095ffa18100013f019a27a1f0115
     */
    'jobTitle'?: string;
}

