/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107AllOf } from './change-job-contract-details-data27ec818d10d010000386ce823ac20107-all-of';
import { Currency2d0ca2cb2448100009c54386a8570e07 } from './currency2d0ca2cb2448100009c54386a8570e07';
import { Frequency2d0ca2cb2448100009c5436d5d670e06 } from './frequency2d0ca2cb2448100009c5436d5d670e06';
import { PurchaseOrder2d0ca2cb2448100009c5433bcff60e05 } from './purchase-order2d0ca2cb2448100009c5433bcff60e05';

/**
 * 
 * @export
 * @interface ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107
 */
export interface ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107 {
    /**
     * The new contract assignment details for the contingent worker as of the effective date.
     * @type {string}
     * @memberof ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107
     */
    'assignmentDetails'?: string;
    /**
     * The contract end date for the position as of this business process.
     * @type {string}
     * @memberof ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107
     */
    'contractEndDate'?: string;
    /**
     * The new contract pay rate for the contingent worker as of the effective date.
     * @type {object}
     * @memberof ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107
     */
    'contractPayRate'?: object;
    /**
     * 
     * @type {Currency2d0ca2cb2448100009c54386a8570e07}
     * @memberof ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107
     */
    'currency'?: Currency2d0ca2cb2448100009c54386a8570e07;
    /**
     * 
     * @type {Frequency2d0ca2cb2448100009c5436d5d670e06}
     * @memberof ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107
     */
    'frequency'?: Frequency2d0ca2cb2448100009c5436d5d670e06;
    /**
     * 
     * @type {PurchaseOrder2d0ca2cb2448100009c5433bcff60e05}
     * @memberof ChangeJobContractDetailsData27ec818d10d010000386ce823ac20107
     */
    'purchaseOrder'?: PurchaseOrder2d0ca2cb2448100009c5433bcff60e05;
}

