/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902ea } from './associated-check-in-topic-detail316b5a26cc3c100010a01184c23902ea';
import { CheckInAttachmentDetailEf244acfe6cf10002ebe92d43a7701d7 } from './check-in-attachment-detail-ef244acfe6cf10002ebe92d43a7701d7';
import { CheckInDetail316b5a26cc3c10000ebdb0cb484602e1AllOf } from './check-in-detail316b5a26cc3c10000ebdb0cb484602e1-all-of';

/**
 * 
 * @export
 * @interface CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
 */
export interface CheckInDetail316b5a26cc3c10000ebdb0cb484602e1 {
    /**
     * Description of check-in.
     * @type {string}
     * @memberof CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
     */
    'description'?: string;
    /**
     * Topics included in a check-in.
     * @type {Array<AssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902ea>}
     * @memberof CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
     */
    'associatedTopics'?: Array<AssociatedCheckInTopicDetail316b5a26cc3c100010a01184c23902ea>;
    /**
     * Date of check-in.
     * @type {string}
     * @memberof CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
     */
    'date': string;
    /**
     * Returns all attachments for the Check-In.
     * @type {Array<CheckInAttachmentDetailEf244acfe6cf10002ebe92d43a7701d7>}
     * @memberof CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
     */
    'checkInAttachments'?: Array<CheckInAttachmentDetailEf244acfe6cf10002ebe92d43a7701d7>;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CheckInDetail316b5a26cc3c10000ebdb0cb484602e1
     */
    'id'?: string;
}

