/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020 } from './associated-check-ins-summary-d81c816de26f10000f7a29ea89140020';
import { CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1 } from './check-in-topic-attachment-detail600ecde4c8421000278d06bfacea01c1';
import { CreatorD81c816de26f10000f521459ac80001d } from './creator-d81c816de26f10000f521459ac80001d';
import { ParticipantD81c816de26f10000f52144d053f001b } from './participant-d81c816de26f10000f52144d053f001b';

/**
 * 
 * @export
 * @interface CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
 */
export interface CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf {
    /**
     * Shared notes of the topic.
     * @type {string}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'sharedNotes'?: string;
    /**
     * Personal notes of the topic.
     * @type {string}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'privateNotes'?: string;
    /**
     * Indicates that the topic is archived.
     * @type {boolean}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'archived'?: boolean;
    /**
     * Topic name.
     * @type {string}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'name'?: string;
    /**
     * Returns all attachments for the Check-In Topic.
     * @type {Array<CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1>}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'checkInTopicAttachments'?: Array<CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1>;
    /**
     * 
     * @type {ParticipantD81c816de26f10000f52144d053f001b}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'participant'?: ParticipantD81c816de26f10000f52144d053f001b;
    /**
     * Check-ins associated to topic.
     * @type {Array<AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020>}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'associatedCheckIns'?: Array<AssociatedCheckInsSummaryD81c816de26f10000f7a29ea89140020>;
    /**
     * 
     * @type {CreatorD81c816de26f10000f521459ac80001d}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'creator'?: CreatorD81c816de26f10000f521459ac80001d;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015AllOf
     */
    'id'?: string;
}

