/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssociatedCheckInDetail3267c0ba92a0100016ed105476ad03c4 } from './associated-check-in-detail3267c0ba92a0100016ed105476ad03c4';
import { CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1 } from './check-in-topic-attachment-detail600ecde4c8421000278d06bfacea01c1';

/**
 * 
 * @export
 * @interface CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf
 */
export interface CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf {
    /**
     * Shared notes of the topic.
     * @type {string}
     * @memberof CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf
     */
    'sharedNotes'?: string;
    /**
     * Check-ins associated to topic.
     * @type {Array<AssociatedCheckInDetail3267c0ba92a0100016ed105476ad03c4>}
     * @memberof CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf
     */
    'associatedCheckIns'?: Array<AssociatedCheckInDetail3267c0ba92a0100016ed105476ad03c4>;
    /**
     * Personal notes of the topic.
     * @type {string}
     * @memberof CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf
     */
    'privateNotes'?: string;
    /**
     * Topic name.
     * @type {string}
     * @memberof CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf
     */
    'name'?: string;
    /**
     * Returns all attachments for the Check-In Topic.
     * @type {Array<CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1>}
     * @memberof CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf
     */
    'checkInTopicAttachments'?: Array<CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1>;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CheckInTopicDetail3267c0ba92a010001688d79b032b03b8AllOf
     */
    'id'?: string;
}

