/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckInTopicArchiveDetail1163fe23102e10001f72d77b213401a2AllOf
 */
export interface CheckInTopicArchiveDetail1163fe23102e10001f72d77b213401a2AllOf {
    /**
     * Indicates that the topic is archived.
     * @type {boolean}
     * @memberof CheckInTopicArchiveDetail1163fe23102e10001f72d77b213401a2AllOf
     */
    'archive': boolean;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CheckInTopicArchiveDetail1163fe23102e10001f72d77b213401a2AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CheckInTopicArchiveDetail1163fe23102e10001f72d77b213401a2AllOf
     */
    'descriptor'?: string;
}

