/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContentType600ecde4c842100027eaa21d044e01cf } from './content-type600ecde4c842100027eaa21d044e01cf';

/**
 * 
 * @export
 * @interface CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf
 */
export interface CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf {
    /**
     * Returns comment for the Attachment
     * @type {string}
     * @memberof CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf
     */
    'comment'?: string;
    /**
     * 
     * @type {ContentType600ecde4c842100027eaa21d044e01cf}
     * @memberof CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf
     */
    'contentType'?: ContentType600ecde4c842100027eaa21d044e01cf;
    /**
     * File name of the attachment
     * @type {string}
     * @memberof CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf
     */
    'fileName'?: string;
    /**
     * File length of the attachment
     * @type {number}
     * @memberof CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf
     */
    'fileLength'?: number;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CheckInTopicAttachmentDetail600ecde4c8421000278d06bfacea01c1AllOf
     */
    'descriptor'?: string;
}

