/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckInArchiveDetail1163fe23102e10001df342088f8a018eAllOf } from './check-in-archive-detail1163fe23102e10001df342088f8a018e-all-of';

/**
 * 
 * @export
 * @interface CheckInArchiveDetail1163fe23102e10001df342088f8a018e
 */
export interface CheckInArchiveDetail1163fe23102e10001df342088f8a018e {
    /**
     * Indicates that the check-in is archived.
     * @type {boolean}
     * @memberof CheckInArchiveDetail1163fe23102e10001df342088f8a018e
     */
    'archive': boolean;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CheckInArchiveDetail1163fe23102e10001df342088f8a018e
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CheckInArchiveDetail1163fe23102e10001df342088f8a018e
     */
    'descriptor'?: string;
}

