/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AssociatedTopicsSummaryB3a69f47a4991000171aae4c5a810040 } from './associated-topics-summary-b3a69f47a4991000171aae4c5a810040';
import { CheckInAttachmentDetailEf244acfe6cf10002ebe92d43a7701d7 } from './check-in-attachment-detail-ef244acfe6cf10002ebe92d43a7701d7';
import { CheckInsSummaryB3a69f47a499100010ce6be72bfe001dAllOf } from './check-ins-summary-b3a69f47a499100010ce6be72bfe001d-all-of';
import { CreatorB3a69f47a49910001687de28dd71003d } from './creator-b3a69f47a49910001687de28dd71003d';
import { ParticipantB3a69f47a49910001687de1d4c75003c } from './participant-b3a69f47a49910001687de1d4c75003c';

/**
 * 
 * @export
 * @interface CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
 */
export interface CheckInsSummaryB3a69f47a499100010ce6be72bfe001d {
    /**
     * Description of check-in.
     * @type {string}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'description'?: string;
    /**
     * Topics included in a check-in.
     * @type {Array<AssociatedTopicsSummaryB3a69f47a4991000171aae4c5a810040>}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'associatedTopics'?: Array<AssociatedTopicsSummaryB3a69f47a4991000171aae4c5a810040>;
    /**
     * 
     * @type {CreatorB3a69f47a49910001687de28dd71003d}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'creator'?: CreatorB3a69f47a49910001687de28dd71003d;
    /**
     * Indicates that the check-in is archived.
     * @type {boolean}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'archived'?: boolean;
    /**
     * Returns all attachments for the Check-In.
     * @type {Array<CheckInAttachmentDetailEf244acfe6cf10002ebe92d43a7701d7>}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'checkInAttachments'?: Array<CheckInAttachmentDetailEf244acfe6cf10002ebe92d43a7701d7>;
    /**
     * 
     * @type {ParticipantB3a69f47a49910001687de1d4c75003c}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'participant'?: ParticipantB3a69f47a49910001687de1d4c75003c;
    /**
     * Date of check-in.
     * @type {string}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'date'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CheckInsSummaryB3a69f47a499100010ce6be72bfe001d
     */
    'id'?: string;
}

