/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Comments7d98fd55aeee100022968e52a1b31c60AllOf
 */
export interface Comments7d98fd55aeee100022968e52a1b31c60AllOf {
    /**
     * The business process comment for a worker event before it\'s submitted.
     * @type {string}
     * @memberof Comments7d98fd55aeee100022968e52a1b31c60AllOf
     */
    'comment'?: string;
}

