/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Person86093b8a932f10001499f38c72410130 } from './person86093b8a932f10001499f38c72410130';

/**
 * 
 * @export
 * @interface Comments86093b8a932f10001499f356ff83012eAllOf
 */
export interface Comments86093b8a932f10001499f356ff83012eAllOf {
    /**
     * Gives the moment at which the instance was originally created.
     * @type {string}
     * @memberof Comments86093b8a932f10001499f356ff83012eAllOf
     */
    'commentDate'?: string;
    /**
     * Comment
     * @type {string}
     * @memberof Comments86093b8a932f10001499f356ff83012eAllOf
     */
    'comment'?: string;
    /**
     * 
     * @type {Person86093b8a932f10001499f38c72410130}
     * @memberof Comments86093b8a932f10001499f356ff83012eAllOf
     */
    'person'?: Person86093b8a932f10001499f38c72410130;
}

