/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryRelatedView7deab99f645f10000cf305c30e260054 } from './country-related-view7deab99f645f10000cf305c30e260054';

/**
 * The \\~country\\~ for the worker compensation code.
 * @export
 * @interface Country3b00708994e4100004edeb4e0d37128c
 */
export interface Country3b00708994e4100004edeb4e0d37128c {
    /**
     * The ISO alpha-3 code for a country.
     * @type {string}
     * @memberof Country3b00708994e4100004edeb4e0d37128c
     */
    'alpha3Code'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof Country3b00708994e4100004edeb4e0d37128c
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof Country3b00708994e4100004edeb4e0d37128c
     */
    'descriptor'?: string;
}

