/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026eAllOf
 */
export interface CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026eAllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026eAllOf
     */
    'descriptor'?: string;
}

