/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CountryRelatedView7deab99f645f10000cf305c30e260054AllOf
 */
export interface CountryRelatedView7deab99f645f10000cf305c30e260054AllOf {
    /**
     * The ISO alpha-3 code for a country.
     * @type {string}
     * @memberof CountryRelatedView7deab99f645f10000cf305c30e260054AllOf
     */
    'alpha3Code'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof CountryRelatedView7deab99f645f10000cf305c30e260054AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryRelatedView7deab99f645f10000cf305c30e260054AllOf
     */
    'descriptor'?: string;
}

