/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryDataForLocationDataAf21e47ff7c01000092e0e4f9a22026e } from './country-data-for-location-data-af21e47ff7c01000092e0e4f9a22026e';

/**
 * Returns the \\~country\\~ from the primary address for the location.
 * @export
 * @interface CountryAf21e47ff7c01000092ecf4d7ad30270
 */
export interface CountryAf21e47ff7c01000092ecf4d7ad30270 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof CountryAf21e47ff7c01000092ecf4d7ad30270
     */
    'descriptor'?: string;
}

