/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225eAllOf } from './create-skill-usage-representation98f198f5056b1000196313ffe9a0225e-all-of';
import { DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8 } from './display-explicit-skill-representation-d6ca778018011000182fa5be1ae901a8';
import { SkillItem98f198f5056b100019631445471d225f } from './skill-item98f198f5056b100019631445471d225f';
import { SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122 } from './skill-item-source-add-representation-c5fabc4ca81610000d5d15309ac90122';

/**
 * 
 * @export
 * @interface CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225e
 */
export interface CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225e {
    /**
     * Explicit Skill Usages
     * @type {Array<DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8>}
     * @memberof CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225e
     */
    'skills'?: Array<DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8>;
    /**
     * 
     * @type {SkillItem98f198f5056b100019631445471d225f}
     * @memberof CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225e
     */
    'skillItem'?: SkillItem98f198f5056b100019631445471d225f;
    /**
     * Skill Sources
     * @type {Array<SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122>}
     * @memberof CreateSkillUsageRepresentation98f198f5056b1000196313ffe9a0225e
     */
    'skillSources'?: Array<SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122>;
}

