/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Creator of \\~topic\\~.
 * @export
 * @interface CreatorD81c816de26f10000f521459ac80001d
 */
export interface CreatorD81c816de26f10000f521459ac80001d {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof CreatorD81c816de26f10000f521459ac80001d
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof CreatorD81c816de26f10000f521459ac80001d
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof CreatorD81c816de26f10000f521459ac80001d
     */
    'href'?: string;
}

