/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DifficultyToFillRelatedView3b00708994e41000032f4de84695004c } from './difficulty-to-fill-related-view3b00708994e41000032f4de84695004c';

/**
 * Indicates how difficult it is to fill this job profile.
 * @export
 * @interface DifficultyToFill89a0b59e7cce1000074acb57c0c50162
 */
export interface DifficultyToFill89a0b59e7cce1000074acb57c0c50162 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof DifficultyToFill89a0b59e7cce1000074acb57c0c50162
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof DifficultyToFill89a0b59e7cce1000074acb57c0c50162
     */
    'descriptor'?: string;
}

