/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ERRORMODELREFERENCE
 */
export interface ERRORMODELREFERENCE {
    /**
     * A description of the error
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'error': string;
    /**
     * The code that corresponds to the error message. Use the error code to drive programmatic error-handling behavior. Don\'t use error message strings for this purpose because they are subject to change
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'code'?: string;
    /**
     * The field related to the error
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'field'?: string;
    /**
     * The path of the field related to the error
     * @type {string}
     * @memberof ERRORMODELREFERENCE
     */
    'path'?: string;
}

