/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Category43b30ba735b8100011ee4781a9d50146 } from './category43b30ba735b8100011ee4781a9d50146';
import { ContentType43b30ba735b8100011ee47993f11014a } from './content-type43b30ba735b8100011ee47993f11014a';
import { UploadedByB32ff437243510000e22e06470370160 } from './uploaded-by-b32ff437243510000e22e06470370160';

/**
 * 
 * @export
 * @interface EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
 */
export interface EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf {
    /**
     * Event attachment description
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'description'?: string;
    /**
     * 
     * @type {ContentType43b30ba735b8100011ee47993f11014a}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'contentType'?: ContentType43b30ba735b8100011ee47993f11014a;
    /**
     * File length of the attachment
     * @type {number}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'fileLength'?: number;
    /**
     * Returns Date the Business Process Attachment was updated.
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'uploadDate'?: string;
    /**
     * File name of the attachment
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'fileName'?: string;
    /**
     * 
     * @type {UploadedByB32ff437243510000e22e06470370160}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'uploadedBy'?: UploadedByB32ff437243510000e22e06470370160;
    /**
     * 
     * @type {Category43b30ba735b8100011ee4781a9d50146}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'category'?: Category43b30ba735b8100011ee4781a9d50146;
    /**
     * Id of the instance
     * @type {string}
     * @memberof EventAttachmentsForToolbar43b30ba735b8100011ee4767246d0143AllOf
     */
    'id'?: string;
}

