/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessProcessParameters23782ad3f54110002073aab65def00fb } from './business-process-parameters23782ad3f54110002073aab65def00fb';
import { EventStateOrganizationAssignmentF3e1ff305e2d100003327f7b7fa103f1AllOf } from './event-state-organization-assignment-f3e1ff305e2d100003327f7b7fa103f1-all-of';

/**
 * 
 * @export
 * @interface EventStateOrganizationAssignmentF3e1ff305e2d100003327f7b7fa103f1
 */
export interface EventStateOrganizationAssignmentF3e1ff305e2d100003327f7b7fa103f1 {
    /**
     * 
     * @type {BusinessProcessParameters23782ad3f54110002073aab65def00fb}
     * @memberof EventStateOrganizationAssignmentF3e1ff305e2d100003327f7b7fa103f1
     */
    'businessProcessParameters'?: BusinessProcessParameters23782ad3f54110002073aab65def00fb;
    /**
     * Id of the instance
     * @type {string}
     * @memberof EventStateOrganizationAssignmentF3e1ff305e2d100003327f7b7fa103f1
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof EventStateOrganizationAssignmentF3e1ff305e2d100003327f7b7fa103f1
     */
    'descriptor'?: string;
}

