/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExternalSkillLevelA39462f09c44100005d46fd77ef00000AllOf
 */
export interface ExternalSkillLevelA39462f09c44100005d46fd77ef00000AllOf {
    /**
     * The skill level normalized to a scale from 1-5 and to 1 decimal place.
     * @type {number}
     * @memberof ExternalSkillLevelA39462f09c44100005d46fd77ef00000AllOf
     */
    'externalSkillLevel': number;
    /**
     * The skill from the external system.
     * @type {string}
     * @memberof ExternalSkillLevelA39462f09c44100005d46fd77ef00000AllOf
     */
    'externalSkillId': string;
    /**
     * The date that the external Skill Level was last updated.
     * @type {string}
     * @memberof ExternalSkillLevelA39462f09c44100005d46fd77ef00000AllOf
     */
    'effectiveMoment'?: string;
    /**
     * The text you enter to provide context for this external skill load. Not visible to end users.
     * @type {string}
     * @memberof ExternalSkillLevelA39462f09c44100005d46fd77ef00000AllOf
     */
    'context'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof ExternalSkillLevelA39462f09c44100005d46fd77ef00000AllOf
     */
    'id'?: string;
}

