/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FACETSMODELREFERENCEInnerValuesInner
 */
export interface FACETSMODELREFERENCEInnerValuesInner {
    /**
     * The number of instances returned by this facet
     * @type {number}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'count'?: number;
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'id': string;
    /**
     * A description of the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof FACETSMODELREFERENCEInnerValuesInner
     */
    'href'?: string;
}

