/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FACETSMODELREFERENCEInnerValuesInner } from './facetsmodelreferenceinner-values-inner';

/**
 * This object represents the possible facets for this resource
 * @export
 * @interface FACETSMODELREFERENCEInner
 */
export interface FACETSMODELREFERENCEInner {
    /**
     * A description of the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInner
     */
    'descriptor'?: string;
    /**
     * The alias used to select the facet
     * @type {string}
     * @memberof FACETSMODELREFERENCEInner
     */
    'facetParameter'?: string;
    /**
     * the facet values
     * @type {Array<FACETSMODELREFERENCEInnerValuesInner>}
     * @memberof FACETSMODELREFERENCEInner
     */
    'values'?: Array<FACETSMODELREFERENCEInnerValuesInner>;
}

