/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The new frequency that is applied to the \\~contingent worker\'s\\~ contract pay rate.
 * @export
 * @interface Frequency2d0ca2cb2448100009c5436d5d670e06
 */
export interface Frequency2d0ca2cb2448100009c5436d5d670e06 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Frequency2d0ca2cb2448100009c5436d5d670e06
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Frequency2d0ca2cb2448100009c5436d5d670e06
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Frequency2d0ca2cb2448100009c5436d5d670e06
     */
    'href'?: string;
}

