/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HomeContactChangeEventF42ba27d87ed10001aa58a5d231b1621AllOf } from './home-contact-change-event-f42ba27d87ed10001aa58a5d231b1621-all-of';

/**
 * 
 * @export
 * @interface HomeContactChangeEventF42ba27d87ed10001aa58a5d231b1621
 */
export interface HomeContactChangeEventF42ba27d87ed10001aa58a5d231b1621 {
    /**
     * The URL to the related change home contact information resource where this event can be interacted with via REST
     * @type {string}
     * @memberof HomeContactChangeEventF42ba27d87ed10001aa58a5d231b1621
     */
    'href'?: string;
    /**
     * The date this business process takes effect.
     * @type {string}
     * @memberof HomeContactChangeEventF42ba27d87ed10001aa58a5d231b1621
     */
    'effective_date'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof HomeContactChangeEventF42ba27d87ed10001aa58a5d231b1621
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof HomeContactChangeEventF42ba27d87ed10001aa58a5d231b1621
     */
    'descriptor'?: string;
}

