/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobTypeDataB8ac205877fd100005c3b50b74a30055AllOf } from './job-type-data-b8ac205877fd100005c3b50b74a30055-all-of';

/**
 * 
 * @export
 * @interface JobTypeDataB8ac205877fd100005c3b50b74a30055
 */
export interface JobTypeDataB8ac205877fd100005c3b50b74a30055 {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobTypeDataB8ac205877fd100005c3b50b74a30055
     */
    'descriptor'?: string;
}

