/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobCategoryRelatedView7deab99f645f10000f8582dc572d0075 } from './job-category-related-view7deab99f645f10000f8582dc572d0075';

/**
 * The Job Category for the Job Profile.
 * @export
 * @interface JobCategory89a0b59e7cce1000074acb471919015f
 */
export interface JobCategory89a0b59e7cce1000074acb471919015f {
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobCategory89a0b59e7cce1000074acb471919015f
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobCategory89a0b59e7cce1000074acb471919015f
     */
    'descriptor'?: string;
}

