/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobDataForWorkerB8ac205877fd10000ea91719a02a00a2AllOf } from './job-data-for-worker-b8ac205877fd10000ea91719a02a00a2-all-of';
import { JobProfileB8ac205877fd10000ea9174f73c500aa } from './job-profile-b8ac205877fd10000ea9174f73c500aa';
import { JobTypeB8ac205877fd10000ea91752f39c00ab } from './job-type-b8ac205877fd10000ea91752f39c00ab';
import { LocationB8ac205877fd10000ea91737c7da00a5 } from './location-b8ac205877fd10000ea91737c7da00a5';
import { SupervisoryOrganizationB8ac205877fd10000ea91743659800a7 } from './supervisory-organization-b8ac205877fd10000ea91743659800a7';
import { WorkSpace426ac445037110001b3eb91ddf6f0100 } from './work-space426ac445037110001b3eb91ddf6f0100';

/**
 * 
 * @export
 * @interface JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
 */
export interface JobDataForWorkerB8ac205877fd10000ea91719a02a00a2 {
    /**
     * The business title for the position.
     * @type {string}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'businessTitle'?: string;
    /**
     * 
     * @type {SupervisoryOrganizationB8ac205877fd10000ea91743659800a7}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'supervisoryOrganization'?: SupervisoryOrganizationB8ac205877fd10000ea91743659800a7;
    /**
     * 
     * @type {JobTypeB8ac205877fd10000ea91752f39c00ab}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'jobType'?: JobTypeB8ac205877fd10000ea91752f39c00ab;
    /**
     * 
     * @type {JobProfileB8ac205877fd10000ea9174f73c500aa}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'jobProfile'?: JobProfileB8ac205877fd10000ea9174f73c500aa;
    /**
     * 
     * @type {LocationB8ac205877fd10000ea91737c7da00a5}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'location'?: LocationB8ac205877fd10000ea91737c7da00a5;
    /**
     * 
     * @type {WorkSpace426ac445037110001b3eb91ddf6f0100}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'workSpace'?: WorkSpace426ac445037110001b3eb91ddf6f0100;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobDataForWorkerB8ac205877fd10000ea91719a02a00a2
     */
    'descriptor'?: string;
}

