/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobCategoryRelatedView7deab99f645f10000f8582dc572d0075AllOf } from './job-category-related-view7deab99f645f10000f8582dc572d0075-all-of';

/**
 * 
 * @export
 * @interface JobCategoryRelatedView7deab99f645f10000f8582dc572d0075
 */
export interface JobCategoryRelatedView7deab99f645f10000f8582dc572d0075 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobCategoryRelatedView7deab99f645f10000f8582dc572d0075
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobCategoryRelatedView7deab99f645f10000f8582dc572d0075
     */
    'descriptor'?: string;
}

