/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobProfileJobViewFab4a151b24810000d511d61ee641262 } from './job-profile-job-view-fab4a151b24810000d511d61ee641262';

/**
 * The job profile for the position.
 * @export
 * @interface JobProfile6fb921f8a11d10001d5268980bbb0097
 */
export interface JobProfile6fb921f8a11d10001d5268980bbb0097 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobProfile6fb921f8a11d10001d5268980bbb0097
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobProfile6fb921f8a11d10001d5268980bbb0097
     */
    'descriptor'?: string;
}

