/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobProfileJobViewFab4a151b24810000d511d61ee641262AllOf } from './job-profile-job-view-fab4a151b24810000d511d61ee641262-all-of';

/**
 * 
 * @export
 * @interface JobProfileJobViewFab4a151b24810000d511d61ee641262
 */
export interface JobProfileJobViewFab4a151b24810000d511d61ee641262 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobProfileJobViewFab4a151b24810000d511d61ee641262
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobProfileJobViewFab4a151b24810000d511d61ee641262
     */
    'descriptor'?: string;
}

