/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobData1bfa8925c50510000ae4479925510026AllOf } from './job-data1bfa8925c50510000ae4479925510026-all-of';
import { JobProfile6fb921f8a11d10001d5268980bbb0097 } from './job-profile6fb921f8a11d10001d5268980bbb0097';
import { JobTypeB8ac205877fd100005c55b45c6400057 } from './job-type-b8ac205877fd100005c55b45c6400057';
import { Location6d3eb084b4c410002b617efb943f0059 } from './location6d3eb084b4c410002b617efb943f0059';
import { SupervisoryOrganizationFab4a151b24810000d13073c5d341257 } from './supervisory-organization-fab4a151b24810000d13073c5d341257';
import { WorkerFab4a151b24810000e66f769304c126b } from './worker-fab4a151b24810000e66f769304c126b';

/**
 * 
 * @export
 * @interface JobData1bfa8925c50510000ae4479925510026
 */
export interface JobData1bfa8925c50510000ae4479925510026 {
    /**
     * 
     * @type {Location6d3eb084b4c410002b617efb943f0059}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'location'?: Location6d3eb084b4c410002b617efb943f0059;
    /**
     * The business title for the position.
     * @type {string}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'businessTitle'?: string;
    /**
     * 
     * @type {WorkerFab4a151b24810000e66f769304c126b}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'worker'?: WorkerFab4a151b24810000e66f769304c126b;
    /**
     * 
     * @type {SupervisoryOrganizationFab4a151b24810000d13073c5d341257}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'supervisoryOrganization'?: SupervisoryOrganizationFab4a151b24810000d13073c5d341257;
    /**
     * The next pay period start date for the job.
     * @type {string}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'nextPayPeriodStartDate'?: string;
    /**
     * 
     * @type {JobTypeB8ac205877fd100005c55b45c6400057}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'jobType'?: JobTypeB8ac205877fd100005c55b45c6400057;
    /**
     * 
     * @type {JobProfile6fb921f8a11d10001d5268980bbb0097}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'jobProfile'?: JobProfile6fb921f8a11d10001d5268980bbb0097;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobData1bfa8925c50510000ae4479925510026
     */
    'descriptor'?: string;
}

