/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobLevelRelatedView7deab99f645f10000f06cbbf927a0069AllOf } from './job-level-related-view7deab99f645f10000f06cbbf927a0069-all-of';

/**
 * 
 * @export
 * @interface JobLevelRelatedView7deab99f645f10000f06cbbf927a0069
 */
export interface JobLevelRelatedView7deab99f645f10000f06cbbf927a0069 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobLevelRelatedView7deab99f645f10000f06cbbf927a0069
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobLevelRelatedView7deab99f645f10000f06cbbf927a0069
     */
    'descriptor'?: string;
}

