/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobFamilyGroup51ed1475e9e6100006229cfe817b0014 } from './job-family-group51ed1475e9e6100006229cfe817b0014';
import { JobFamilyView51ed1475e9e6100005d10fcedc5a000aAllOf } from './job-family-view51ed1475e9e6100005d10fcedc5a000a-all-of';
import { JobProfileView51ed1475e9e6100006c698ef68480017 } from './job-profile-view51ed1475e9e6100006c698ef68480017';

/**
 * 
 * @export
 * @interface JobFamilyView51ed1475e9e6100005d10fcedc5a000a
 */
export interface JobFamilyView51ed1475e9e6100005d10fcedc5a000a {
    /**
     * Returns the job family summary for the job family.
     * @type {string}
     * @memberof JobFamilyView51ed1475e9e6100005d10fcedc5a000a
     */
    'summary'?: string;
    /**
     * If true, the method returns inactive job families. Default is false.
     * @type {boolean}
     * @memberof JobFamilyView51ed1475e9e6100005d10fcedc5a000a
     */
    'inactive'?: boolean;
    /**
     * 
     * @type {JobFamilyGroup51ed1475e9e6100006229cfe817b0014}
     * @memberof JobFamilyView51ed1475e9e6100005d10fcedc5a000a
     */
    'jobFamilyGroup'?: JobFamilyGroup51ed1475e9e6100006229cfe817b0014;
    /**
     * The job profile for the job family. You can specify more than 1 jobFamilyGroup query parameter. For possible values, you can use a returned id from GET /jobProfiles.
     * @type {Array<JobProfileView51ed1475e9e6100006c698ef68480017>}
     * @memberof JobFamilyView51ed1475e9e6100005d10fcedc5a000a
     */
    'jobProfiles'?: Array<JobProfileView51ed1475e9e6100006c698ef68480017>;
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobFamilyView51ed1475e9e6100005d10fcedc5a000a
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobFamilyView51ed1475e9e6100005d10fcedc5a000a
     */
    'descriptor'?: string;
}

