/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobTypeDataB8ac205877fd100005c3b50b74a30055 } from './job-type-data-b8ac205877fd100005c3b50b74a30055';

/**
 * The position\'s job type which can be one of the following values: Primary, Additional Job, or International Assignment. If the position is not effective, no value will be returned. Primary and additional job are effective dated due to the Switch Primary Job business process. An international assignment cannot be switched to a be a primary job.
 * @export
 * @interface JobTypeB8ac205877fd10000ea91752f39c00ab
 */
export interface JobTypeB8ac205877fd10000ea91752f39c00ab {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobTypeB8ac205877fd10000ea91752f39c00ab
     */
    'descriptor'?: string;
}

