/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryOrRegion3b00708994e4100007848bc917a112a6 } from './country-or-region3b00708994e4100007848bc917a112a6';
import { JobProfileExemptRelatedView3b00708994e41000076da515387812a2AllOf } from './job-profile-exempt-related-view3b00708994e41000076da515387812a2-all-of';

/**
 * 
 * @export
 * @interface JobProfileExemptRelatedView3b00708994e41000076da515387812a2
 */
export interface JobProfileExemptRelatedView3b00708994e41000076da515387812a2 {
    /**
     * 
     * @type {CountryOrRegion3b00708994e4100007848bc917a112a6}
     * @memberof JobProfileExemptRelatedView3b00708994e41000076da515387812a2
     */
    'countryOrRegion'?: CountryOrRegion3b00708994e4100007848bc917a112a6;
    /**
     * Returns the exempt value for this Job Profile Exempt.
     * @type {boolean}
     * @memberof JobProfileExemptRelatedView3b00708994e41000076da515387812a2
     */
    'exempt'?: boolean;
}

