/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobLevelRelatedView7deab99f645f10000f06cbbf927a0069 } from './job-level-related-view7deab99f645f10000f06cbbf927a0069';

/**
 * The job level for the job profile.
 * @export
 * @interface JobLevel89a0b59e7cce1000074acb3c1e8e015d
 */
export interface JobLevel89a0b59e7cce1000074acb3c1e8e015d {
    /**
     * Id of the instance
     * @type {string}
     * @memberof JobLevel89a0b59e7cce1000074acb3c1e8e015d
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof JobLevel89a0b59e7cce1000074acb3c1e8e015d
     */
    'descriptor'?: string;
}

