/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobFamilyView51ed1475e9e6100005d10fcedc5a000a } from './job-family-view51ed1475e9e6100005d10fcedc5a000a';

/**
 * 
 * @export
 * @interface JobFamiliesListResponse
 */
export interface JobFamiliesListResponse {
    /**
     * 
     * @type {Array<JobFamilyView51ed1475e9e6100005d10fcedc5a000a>}
     * @memberof JobFamiliesListResponse
     */
    'data'?: Array<JobFamilyView51ed1475e9e6100005d10fcedc5a000a>;
    /**
     * 
     * @type {number}
     * @memberof JobFamiliesListResponse
     */
    'total'?: number;
}

