/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobProfileSummaryView7deab99f645f10000b5152ce2d700034 } from './job-profile-summary-view7deab99f645f10000b5152ce2d700034';

/**
 * 
 * @export
 * @interface JobProfilesListCollectionResponse
 */
export interface JobProfilesListCollectionResponse {
    /**
     * 
     * @type {Array<JobProfileSummaryView7deab99f645f10000b5152ce2d700034>}
     * @memberof JobProfilesListCollectionResponse
     */
    'data'?: Array<JobProfileSummaryView7deab99f645f10000b5152ce2d700034>;
    /**
     * 
     * @type {number}
     * @memberof JobProfilesListCollectionResponse
     */
    'total'?: number;
}

