/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobJobClassificationData354103f196361000084489bcb281017f } from './change-job-job-classification-data354103f196361000084489bcb281017f';

/**
 * 
 * @export
 * @interface JobChangesGetJobClassificationResponse
 */
export interface JobChangesGetJobClassificationResponse {
    /**
     * 
     * @type {Array<ChangeJobJobClassificationData354103f196361000084489bcb281017f>}
     * @memberof JobChangesGetJobClassificationResponse
     */
    'data'?: Array<ChangeJobJobClassificationData354103f196361000084489bcb281017f>;
    /**
     * 
     * @type {number}
     * @memberof JobChangesGetJobClassificationResponse
     */
    'total'?: number;
}

