/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221 } from './change-job-position-data-dfc4e58f7308100018bd1c459f435221';

/**
 * 
 * @export
 * @interface JobChangesGetPositionByIdResponse
 */
export interface JobChangesGetPositionByIdResponse {
    /**
     * 
     * @type {Array<ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221>}
     * @memberof JobChangesGetPositionByIdResponse
     */
    'data'?: Array<ChangeJobPositionDataDfc4e58f7308100018bd1c459f435221>;
    /**
     * 
     * @type {number}
     * @memberof JobChangesGetPositionByIdResponse
     */
    'total'?: number;
}

