/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country3b00708994e41000095e4647007012bc } from './country3b00708994e41000095e4647007012bc';
import { PayRateType3b00708994e410000c3d01aea96012c1 } from './pay-rate-type3b00708994e410000c3d01aea96012c1';

/**
 * 
 * @export
 * @interface JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5AllOf
 */
export interface JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5AllOf {
    /**
     * 
     * @type {PayRateType3b00708994e410000c3d01aea96012c1}
     * @memberof JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5AllOf
     */
    'payRateType'?: PayRateType3b00708994e410000c3d01aea96012c1;
    /**
     * 
     * @type {Country3b00708994e41000095e4647007012bc}
     * @memberof JobProfilePayRateTypeRelatedView3b00708994e4100008d4b09e903f12b5AllOf
     */
    'country'?: Country3b00708994e41000095e4647007012bc;
}

