/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobChangesStartDetailsDataCe861a6a360d10002d40f176b7180020 } from './job-changes-start-details-data-ce861a6a360d10002d40f176b7180020';

/**
 * 
 * @export
 * @interface JobChangesGetStartDetailsResponse
 */
export interface JobChangesGetStartDetailsResponse {
    /**
     * 
     * @type {Array<JobChangesStartDetailsDataCe861a6a360d10002d40f176b7180020>}
     * @memberof JobChangesGetStartDetailsResponse
     */
    'data'?: Array<JobChangesStartDetailsDataCe861a6a360d10002d40f176b7180020>;
    /**
     * 
     * @type {number}
     * @memberof JobChangesGetStartDetailsResponse
     */
    'total'?: number;
}

