/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The new job profile for the \\~worker\\~ as of the effective date.
 * @export
 * @interface JobProfile3db8095ffa18100013f019afc6d30116
 */
export interface JobProfile3db8095ffa18100013f019afc6d30116 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof JobProfile3db8095ffa18100013f019afc6d30116
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof JobProfile3db8095ffa18100013f019afc6d30116
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof JobProfile3db8095ffa18100013f019afc6d30116
     */
    'href'?: string;
}

