/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The position for the \\~worker\\~ prior to the effective date.  This field will be blank for non-staffing transactions and for hire transactions.
 * @export
 * @interface Job75e528a78e9a10000ab7512c5c550115
 */
export interface Job75e528a78e9a10000ab7512c5c550115 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Job75e528a78e9a10000ab7512c5c550115
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Job75e528a78e9a10000ab7512c5c550115
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Job75e528a78e9a10000ab7512c5c550115
     */
    'href'?: string;
}

