/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ManagementLevelRelatedView7deab99f645f10000d69adf2c932005cAllOf } from './management-level-related-view7deab99f645f10000d69adf2c932005c-all-of';

/**
 * 
 * @export
 * @interface ManagementLevelRelatedView7deab99f645f10000d69adf2c932005c
 */
export interface ManagementLevelRelatedView7deab99f645f10000d69adf2c932005c {
    /**
     * Id of the instance
     * @type {string}
     * @memberof ManagementLevelRelatedView7deab99f645f10000d69adf2c932005c
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ManagementLevelRelatedView7deab99f645f10000d69adf2c932005c
     */
    'descriptor'?: string;
}

