/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ManagerWorkerViewA02c2e1916fa10000cbb84be81ce0027AllOf
 */
export interface ManagerWorkerViewA02c2e1916fa10000cbb84be81ce0027AllOf {
    /**
     * Id of the instance
     * @type {string}
     * @memberof ManagerWorkerViewA02c2e1916fa10000cbb84be81ce0027AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ManagerWorkerViewA02c2e1916fa10000cbb84be81ce0027AllOf
     */
    'descriptor'?: string;
}

