/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ManagementLevelRelatedView7deab99f645f10000d69adf2c932005c } from './management-level-related-view7deab99f645f10000d69adf2c932005c';

/**
 * The management level for the job profile.
 * @export
 * @interface ManagementLevel89a0b59e7cce1000074acb1d768e0158
 */
export interface ManagementLevel89a0b59e7cce1000074acb1d768e0158 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof ManagementLevel89a0b59e7cce1000074acb1d768e0158
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof ManagementLevel89a0b59e7cce1000074acb1d768e0158
     */
    'descriptor'?: string;
}

