/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns the Mass Action Worksheet instance.
 * @export
 * @interface MassActionWorksheet31485c9a93c0100007276cf4e5640000
 */
export interface MassActionWorksheet31485c9a93c0100007276cf4e5640000 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof MassActionWorksheet31485c9a93c0100007276cf4e5640000
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof MassActionWorksheet31485c9a93c0100007276cf4e5640000
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof MassActionWorksheet31485c9a93c0100007276cf4e5640000
     */
    'href'?: string;
}

