/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrganizationAssignmentChangesStartDetailsData90009f2bfc49100017b10cd07d19063b } from './organization-assignment-changes-start-details-data90009f2bfc49100017b10cd07d19063b';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesGetStartDetailsResponse
 */
export interface OrganizationAssignmentChangesGetStartDetailsResponse {
    /**
     * 
     * @type {Array<OrganizationAssignmentChangesStartDetailsData90009f2bfc49100017b10cd07d19063b>}
     * @memberof OrganizationAssignmentChangesGetStartDetailsResponse
     */
    'data'?: Array<OrganizationAssignmentChangesStartDetailsData90009f2bfc49100017b10cd07d19063b>;
    /**
     * 
     * @type {number}
     * @memberof OrganizationAssignmentChangesGetStartDetailsResponse
     */
    'total'?: number;
}

