/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FundA18edb56aca0100014a4a0b27352045c } from './fund-a18edb56aca0100014a4a0b27352045c';
import { GiftA18edb56aca0100014a4a0a9f876045b } from './gift-a18edb56aca0100014a4a0a9f876045b';
import { GrantA18edb56aca0100014a4a0bcf25c045e } from './grant-a18edb56aca0100014a4a0bcf25c045e';
import { ProgramA18edb56aca0100014a4a0b7ddf7045d } from './program-a18edb56aca0100014a4a0b7ddf7045d';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045aAllOf
 */
export interface OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045aAllOf {
    /**
     * 
     * @type {GrantA18edb56aca0100014a4a0bcf25c045e}
     * @memberof OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045aAllOf
     */
    'grant'?: GrantA18edb56aca0100014a4a0bcf25c045e;
    /**
     * 
     * @type {ProgramA18edb56aca0100014a4a0b7ddf7045d}
     * @memberof OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045aAllOf
     */
    'program'?: ProgramA18edb56aca0100014a4a0b7ddf7045d;
    /**
     * 
     * @type {GiftA18edb56aca0100014a4a0a9f876045b}
     * @memberof OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045aAllOf
     */
    'gift'?: GiftA18edb56aca0100014a4a0a9f876045b;
    /**
     * 
     * @type {FundA18edb56aca0100014a4a0b27352045c}
     * @memberof OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045aAllOf
     */
    'fund'?: FundA18edb56aca0100014a4a0b27352045c;
}

