/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045a } from './organization-assignment-changes-costing-data-a18edb56aca0100014a4a09dc57e045a';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesGetCostingOrganizationsResponse
 */
export interface OrganizationAssignmentChangesGetCostingOrganizationsResponse {
    /**
     * 
     * @type {Array<OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045a>}
     * @memberof OrganizationAssignmentChangesGetCostingOrganizationsResponse
     */
    'data'?: Array<OrganizationAssignmentChangesCostingDataA18edb56aca0100014a4a09dc57e045a>;
    /**
     * 
     * @type {number}
     * @memberof OrganizationAssignmentChangesGetCostingOrganizationsResponse
     */
    'total'?: number;
}

