/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Comments7d98fd55aeee100022968e52a1b31c60 } from './comments7d98fd55aeee100022968e52a1b31c60';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesGetCommentResponse
 */
export interface OrganizationAssignmentChangesGetCommentResponse {
    /**
     * 
     * @type {Array<Comments7d98fd55aeee100022968e52a1b31c60>}
     * @memberof OrganizationAssignmentChangesGetCommentResponse
     */
    'data'?: Array<Comments7d98fd55aeee100022968e52a1b31c60>;
    /**
     * 
     * @type {number}
     * @memberof OrganizationAssignmentChangesGetCommentResponse
     */
    'total'?: number;
}

