/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MassActionHeaderCf97466f96d910002bd32afbf0000001 } from './mass-action-header-cf97466f96d910002bd32afbf0000001';
import { MassActionWorksheet31485c9a93c0100007276cf4e5640000 } from './mass-action-worksheet31485c9a93c0100007276cf4e5640000';
import { OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000AllOf } from './organization-assignment-changes-post-position-cf97466f96d9100029bffcf91c120000-all-of';
import { PositionCf97466f96d9100029bffcf91c120001 } from './position-cf97466f96d9100029bffcf91c120001';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
 */
export interface OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000 {
    /**
     * 
     * @type {PositionCf97466f96d9100029bffcf91c120001}
     * @memberof OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
     */
    'position': PositionCf97466f96d9100029bffcf91c120001;
    /**
     * 
     * @type {MassActionWorksheet31485c9a93c0100007276cf4e5640000}
     * @memberof OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
     */
    'massActionWorksheet'?: MassActionWorksheet31485c9a93c0100007276cf4e5640000;
    /**
     * 
     * @type {MassActionHeaderCf97466f96d910002bd32afbf0000001}
     * @memberof OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
     */
    'massActionHeader'?: MassActionHeaderCf97466f96d910002bd32afbf0000001;
    /**
     * The effective date of the business process event using the yyyy-mm-dd format.
     * @type {string}
     * @memberof OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
     */
    'date': string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof OrganizationAssignmentChangesPostPositionCf97466f96d9100029bffcf91c120000
     */
    'descriptor'?: string;
}

