/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CustomOrganizationDetails3950e273020a100017857926d35d369c } from './custom-organization-details3950e273020a100017857926d35d369c';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf
 */
export interface OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf {
    /**
     * The new custom organizations for the worker as of the effective date.
     * @type {Array<CustomOrganizationDetails3950e273020a100017857926d35d369c>}
     * @memberof OrganizationAssignmentChangesCustomOrganizationDetailsData53cd2b632146100011e9bf4e7041551fAllOf
     */
    'customOrganizations'?: Array<CustomOrganizationDetails3950e273020a100017857926d35d369c>;
}

