/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Includes these organization types: Company, Cost Center, Custom orgs, Location Hierarchy, Matrix, Pay Group, Region, Retiree, Supervisory.
 * @export
 * @interface OrganizationType3950e273020a100017857958e234369d
 */
export interface OrganizationType3950e273020a100017857958e234369d {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof OrganizationType3950e273020a100017857958e234369d
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof OrganizationType3950e273020a100017857958e234369d
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof OrganizationType3950e273020a100017857958e234369d
     */
    'href'?: string;
}

