/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CostCenter5aabf8e28cb3100010a999f40b07024f } from './cost-center5aabf8e28cb3100010a999f40b07024f';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024eAllOf
 */
export interface OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024eAllOf {
    /**
     * 
     * @type {CostCenter5aabf8e28cb3100010a999f40b07024f}
     * @memberof OrganizationAssignmentChangesCostCenterData5aabf8e28cb3100010a999db2700024eAllOf
     */
    'costCenter'?: CostCenter5aabf8e28cb3100010a999f40b07024f;
}

