/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BusinessUnit5aabf8e28cb310002520b2aabc470366 } from './business-unit5aabf8e28cb310002520b2aabc470366';
import { OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365AllOf } from './organization-assignment-changes-business-unit-data5aabf8e28cb310002520b2a2b31d0365-all-of';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365
 */
export interface OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365 {
    /**
     * 
     * @type {BusinessUnit5aabf8e28cb310002520b2aabc470366}
     * @memberof OrganizationAssignmentChangesBusinessUnitData5aabf8e28cb310002520b2a2b31d0365
     */
    'businessUnit'?: BusinessUnit5aabf8e28cb310002520b2aabc470366;
}

