/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RegionA18edb56aca0100006997ec7e07d0374 } from './region-a18edb56aca0100006997ec7e07d0374';

/**
 * 
 * @export
 * @interface OrganizationAssignmentChangesRegionDataA18edb56aca0100006997e68e5780373AllOf
 */
export interface OrganizationAssignmentChangesRegionDataA18edb56aca0100006997e68e5780373AllOf {
    /**
     * 
     * @type {RegionA18edb56aca0100006997ec7e07d0374}
     * @memberof OrganizationAssignmentChangesRegionDataA18edb56aca0100006997e68e5780373AllOf
     */
    'region'?: RegionA18edb56aca0100006997ec7e07d0374;
}

