/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Returns the Top Level (overall) Business Process that this Event is part of or returns the same instance if this Event is not a sub-process.
 * @export
 * @interface OverallBusinessProcess5d688bd57bb910001815ab49927724aa
 */
export interface OverallBusinessProcess5d688bd57bb910001815ab49927724aa {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof OverallBusinessProcess5d688bd57bb910001815ab49927724aa
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof OverallBusinessProcess5d688bd57bb910001815ab49927724aa
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof OverallBusinessProcess5d688bd57bb910001815ab49927724aa
     */
    'href'?: string;
}

