/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Participant of \\~check-in\\~.
 * @export
 * @interface ParticipantB3a69f47a49910001687de1d4c75003c
 */
export interface ParticipantB3a69f47a49910001687de1d4c75003c {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof ParticipantB3a69f47a49910001687de1d4c75003c
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof ParticipantB3a69f47a49910001687de1d4c75003c
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof ParticipantB3a69f47a49910001687de1d4c75003c
     */
    'href'?: string;
}

