/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayRateTypeRelatedView3b00708994e410000c52776049ba12c3AllOf } from './pay-rate-type-related-view3b00708994e410000c52776049ba12c3-all-of';

/**
 * 
 * @export
 * @interface PayRateTypeRelatedView3b00708994e410000c52776049ba12c3
 */
export interface PayRateTypeRelatedView3b00708994e410000c52776049ba12c3 {
    /**
     * Id of the instance
     * @type {string}
     * @memberof PayRateTypeRelatedView3b00708994e410000c52776049ba12c3
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof PayRateTypeRelatedView3b00708994e410000c52776049ba12c3
     */
    'descriptor'?: string;
}

