/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PersonDataViewBe343791f59d100028d6a277ca8a0017AllOf } from './person-data-view-be343791f59d100028d6a277ca8a0017-all-of';

/**
 * 
 * @export
 * @interface PersonDataViewBe343791f59d100028d6a277ca8a0017
 */
export interface PersonDataViewBe343791f59d100028d6a277ca8a0017 {
    /**
     * Returns the primary public work phone number for the worker.
     * @type {string}
     * @memberof PersonDataViewBe343791f59d100028d6a277ca8a0017
     */
    'phone'?: string;
    /**
     * Returns the public primary work email address for the worker.
     * @type {string}
     * @memberof PersonDataViewBe343791f59d100028d6a277ca8a0017
     */
    'email'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof PersonDataViewBe343791f59d100028d6a277ca8a0017
     */
    'id'?: string;
}

