/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The new program for the \\~worker\\~ after the business process.
 * @export
 * @interface ProgramA18edb56aca0100014a4a0b7ddf7045d
 */
export interface ProgramA18edb56aca0100014a4a0b7ddf7045d {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof ProgramA18edb56aca0100014a4a0b7ddf7045d
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof ProgramA18edb56aca0100014a4a0b7ddf7045d
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof ProgramA18edb56aca0100014a4a0b7ddf7045d
     */
    'href'?: string;
}

