/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The business process type, reason category and reason associated with the business process (e.g. Hire \\~Employee\\~ > New Hire > New Position).
 * @export
 * @interface Reason85deac43cd1a10000b96c80c118f171e
 */
export interface Reason85deac43cd1a10000b96c80c118f171e {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Reason85deac43cd1a10000b96c80c118f171e
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Reason85deac43cd1a10000b96c80c118f171e
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Reason85deac43cd1a10000b96c80c118f171e
     */
    'href'?: string;
}

