/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The business process type, reason category and reason associated with the business process (e.g. Hire \\~Employee\\~ > New Hire > New Position).
 * @export
 * @interface Reason6da81665c26510001f34d0a154765e9b
 */
export interface Reason6da81665c26510001f34d0a154765e9b {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Reason6da81665c26510001f34d0a154765e9b
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Reason6da81665c26510001f34d0a154765e9b
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Reason6da81665c26510001f34d0a154765e9b
     */
    'href'?: string;
}

