/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RegionRelatedView3b00708994e41000053151ffd9e31293AllOf
 */
export interface RegionRelatedView3b00708994e41000053151ffd9e31293AllOf {
    /**
     * A preview of the instance
     * @type {string}
     * @memberof RegionRelatedView3b00708994e41000053151ffd9e31293AllOf
     */
    'descriptor'?: string;
}

