/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceDatesData6b1db753fd82100027b0c8519c860018AllOf } from './service-dates-data6b1db753fd82100027b0c8519c860018-all-of';

/**
 * 
 * @export
 * @interface ServiceDatesData6b1db753fd82100027b0c8519c860018
 */
export interface ServiceDatesData6b1db753fd82100027b0c8519c860018 {
    /**
     * The worker\'s most recent hire date.
     * @type {string}
     * @memberof ServiceDatesData6b1db753fd82100027b0c8519c860018
     */
    'hireDate'?: string;
    /**
     * Worker service date taking into account breaks in service.
     * @type {string}
     * @memberof ServiceDatesData6b1db753fd82100027b0c8519c860018
     */
    'continuousServiceDate'?: string;
}

