/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillItemAddDefinitionFaed9891d75a10001e9a289910540228 } from './skill-item-add-definition-faed9891d75a10001e9a289910540228';
import { SkillItemsBulkDefinition9d815bbfd67010000d6ed56204ab12deAllOf } from './skill-items-bulk-definition9d815bbfd67010000d6ed56204ab12de-all-of';

/**
 * 
 * @export
 * @interface SkillItemsBulkDefinition9d815bbfd67010000d6ed56204ab12de
 */
export interface SkillItemsBulkDefinition9d815bbfd67010000d6ed56204ab12de {
    /**
     * Exposes Skill Items for a Skill Qualification Enabled.
     * @type {Array<SkillItemAddDefinitionFaed9891d75a10001e9a289910540228>}
     * @memberof SkillItemsBulkDefinition9d815bbfd67010000d6ed56204ab12de
     */
    'skillItems'?: Array<SkillItemAddDefinitionFaed9891d75a10001e9a289910540228>;
}

