/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * a set containing no instances
 * @export
 * @interface SkillSourceC5fabc4ca81610000d5d154e6e3c0123
 */
export interface SkillSourceC5fabc4ca81610000d5d154e6e3c0123 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof SkillSourceC5fabc4ca81610000d5d154e6e3c0123
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof SkillSourceC5fabc4ca81610000d5d154e6e3c0123
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof SkillSourceC5fabc4ca81610000d5d154e6e3c0123
     */
    'href'?: string;
}

