/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8AllOf
 */
export interface SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8AllOf {
    /**
     * The Source Type of this Skill Item Source
     * @type {string}
     * @memberof SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8AllOf
     */
    'sourceType'?: string;
    /**
     * source type ID
     * @type {string}
     * @memberof SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8AllOf
     */
    'sourceTypeID'?: string;
    /**
     * The Creation Date of this Skill Item Source
     * @type {string}
     * @memberof SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8AllOf
     */
    'dateCreated'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof SkillSourceRepresentation998d2cc58f2f10000db59b08da0306a8AllOf
     */
    'descriptor'?: string;
}

