/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillSourceC5fabc4ca81610000d5d154e6e3c0123 } from './skill-source-c5fabc4ca81610000d5d154e6e3c0123';

/**
 * 
 * @export
 * @interface SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122AllOf
 */
export interface SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122AllOf {
    /**
     * 
     * @type {SkillSourceC5fabc4ca81610000d5d154e6e3c0123}
     * @memberof SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122AllOf
     */
    'skillSource'?: SkillSourceC5fabc4ca81610000d5d154e6e3c0123;
    /**
     * Id of the instance
     * @type {string}
     * @memberof SkillItemSourceAddRepresentationC5fabc4ca81610000d5d15309ac90122AllOf
     */
    'id'?: string;
}

