/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillItemAddRepresentationC5fabc4ca81610000eaeb4ff2f000137 } from './skill-item-add-representation-c5fabc4ca81610000eaeb4ff2f000137';

/**
 * a set containing no instances
 * @export
 * @interface SkillItem98f198f5056b100019631445471d225f
 */
export interface SkillItem98f198f5056b100019631445471d225f {
    /**
     * The skill name Workday returns.
     * @type {string}
     * @memberof SkillItem98f198f5056b100019631445471d225f
     */
    'skillName'?: string;
    /**
     * The remote skill ID of a skill.
     * @type {string}
     * @memberof SkillItem98f198f5056b100019631445471d225f
     */
    'remoteID'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof SkillItem98f198f5056b100019631445471d225f
     */
    'id'?: string;
}

