/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * Transaction status or workflow state for an event. Example: Successfully Completed, Denied, Terminated
 * @export
 * @interface Status54e611eca2c910000fbc4599be0b0112
 */
export interface Status54e611eca2c910000fbc4599be0b0112 {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Status54e611eca2c910000fbc4599be0b0112
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Status54e611eca2c910000fbc4599be0b0112
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Status54e611eca2c910000fbc4599be0b0112
     */
    'href'?: string;
}

