/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ManagerWorkerViewA02c2e1916fa10000cbb84be81ce0027 } from './manager-worker-view-a02c2e1916fa10000cbb84be81ce0027';

/**
 * 
 * @export
 * @interface SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf
 */
export interface SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf {
    /**
     * Returns the name of the organization as of the processing effective moment
     * @type {string}
     * @memberof SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf
     */
    'name'?: string;
    /**
     * The manager(s) for the supervisory organization.
     * @type {Array<ManagerWorkerViewA02c2e1916fa10000cbb84be81ce0027>}
     * @memberof SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf
     */
    'managers'?: Array<ManagerWorkerViewA02c2e1916fa10000cbb84be81ce0027>;
    /**
     * The organization id for the organization.
     * @type {string}
     * @memberof SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf
     */
    'code'?: string;
    /**
     * Indicates whether the organization is inactive
     * @type {boolean}
     * @memberof SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf
     */
    'inactive'?: boolean;
    /**
     * Id of the instance
     * @type {string}
     * @memberof SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018AllOf
     */
    'descriptor'?: string;
}

