/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrgChartView643e3a12629710000554e0338e670044 } from './org-chart-view643e3a12629710000554e0338e670044';

/**
 * 
 * @export
 * @interface SupervisoryOrganizationsGetOrgChartResponse
 */
export interface SupervisoryOrganizationsGetOrgChartResponse {
    /**
     * 
     * @type {Array<OrgChartView643e3a12629710000554e0338e670044>}
     * @memberof SupervisoryOrganizationsGetOrgChartResponse
     */
    'data'?: Array<OrgChartView643e3a12629710000554e0338e670044>;
    /**
     * 
     * @type {number}
     * @memberof SupervisoryOrganizationsGetOrgChartResponse
     */
    'total'?: number;
}

