/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018 } from './supervisory-organization-view-a02c2e1916fa100009e137235f1f0018';

/**
 * 
 * @export
 * @interface SupervisoryOrganizationsGetByIdResponse
 */
export interface SupervisoryOrganizationsGetByIdResponse {
    /**
     * 
     * @type {Array<SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018>}
     * @memberof SupervisoryOrganizationsGetByIdResponse
     */
    'data'?: Array<SupervisoryOrganizationViewA02c2e1916fa100009e137235f1f0018>;
    /**
     * 
     * @type {number}
     * @memberof SupervisoryOrganizationsGetByIdResponse
     */
    'total'?: number;
}

