/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobData1bfa8925c50510000ae4479925510026 } from './job-data1bfa8925c50510000ae4479925510026';

/**
 * 
 * @export
 * @interface SupervisoryOrganizationsGetMembersResponse
 */
export interface SupervisoryOrganizationsGetMembersResponse {
    /**
     * 
     * @type {Array<JobData1bfa8925c50510000ae4479925510026>}
     * @memberof SupervisoryOrganizationsGetMembersResponse
     */
    'data'?: Array<JobData1bfa8925c50510000ae4479925510026>;
    /**
     * 
     * @type {number}
     * @memberof SupervisoryOrganizationsGetMembersResponse
     */
    'total'?: number;
}

