/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { INSTANCEMODELREFERENCE } from './instancemodelreference';

/**
 * The Change Job Template used to initiate the Change Job event.
 * @export
 * @interface Template2b1b95dfe4af100007f63081aec5158e
 */
export interface Template2b1b95dfe4af100007f63081aec5158e {
    /**
     * wid / id / reference id
     * @type {string}
     * @memberof Template2b1b95dfe4af100007f63081aec5158e
     */
    'id': string;
    /**
     * A description of the instance
     * @type {string}
     * @memberof Template2b1b95dfe4af100007f63081aec5158e
     */
    'descriptor'?: string;
    /**
     * A link to the instance
     * @type {string}
     * @memberof Template2b1b95dfe4af100007f63081aec5158e
     */
    'href'?: string;
}

