/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ERRORMODELREFERENCE } from './errormodelreference';

/**
 * 
 * @export
 * @interface VALIDATIONERRORMODELREFERENCEAllOf
 */
export interface VALIDATIONERRORMODELREFERENCEAllOf {
    /**
     * A description of the error
     * @type {string}
     * @memberof VALIDATIONERRORMODELREFERENCEAllOf
     */
    'error': string;
    /**
     * An array of validation errors
     * @type {Array<ERRORMODELREFERENCE>}
     * @memberof VALIDATIONERRORMODELREFERENCEAllOf
     */
    'errors'?: Array<ERRORMODELREFERENCE>;
}

