/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Country3b00708994e4100004edeb4e0d37128c } from './country3b00708994e4100004edeb4e0d37128c';
import { LocationDataJobView6d3eb084b4c410002b5fa13f0c9d0056 } from './location-data-job-view6d3eb084b4c410002b5fa13f0c9d0056';
import { RegionRelatedView3b00708994e41000053151ffd9e31293 } from './region-related-view3b00708994e41000053151ffd9e31293';
import { WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287AllOf } from './workers-compensation-code-related-view3b00708994e4100004af13d958811287-all-of';

/**
 * 
 * @export
 * @interface WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
 */
export interface WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287 {
    /**
     * Returns true if the worker\'s compensation code is inactive.
     * @type {boolean}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'inactive'?: boolean;
    /**
     * Returns the description of the worker\'s compensation code.
     * @type {string}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'name'?: string;
    /**
     * Returns the Country Regions that the worker\'s compensation code is used in.
     * @type {Array<RegionRelatedView3b00708994e41000053151ffd9e31293>}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'regions'?: Array<RegionRelatedView3b00708994e41000053151ffd9e31293>;
    /**
     * 
     * @type {Country3b00708994e4100004edeb4e0d37128c}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'country'?: Country3b00708994e4100004edeb4e0d37128c;
    /**
     * The location for the worker compensation code.
     * @type {Array<LocationDataJobView6d3eb084b4c410002b5fa13f0c9d0056>}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'locations'?: Array<LocationDataJobView6d3eb084b4c410002b5fa13f0c9d0056>;
    /**
     * Returns the workers\' compensation code.
     * @type {string}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'code'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof WorkersCompensationCodeRelatedView3b00708994e4100004af13d958811287
     */
    'descriptor'?: string;
}

