/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkContactChangeEvent5fca6c96c1c81000142fd03784140113AllOf } from './work-contact-change-event5fca6c96c1c81000142fd03784140113-all-of';

/**
 * 
 * @export
 * @interface WorkContactChangeEvent5fca6c96c1c81000142fd03784140113
 */
export interface WorkContactChangeEvent5fca6c96c1c81000142fd03784140113 {
    /**
     * The date this business process takes effect.
     * @type {string}
     * @memberof WorkContactChangeEvent5fca6c96c1c81000142fd03784140113
     */
    'effective_date'?: string;
    /**
     * The URL to the related change work contact information resource where this event can be interacted with via REST.
     * @type {string}
     * @memberof WorkContactChangeEvent5fca6c96c1c81000142fd03784140113
     */
    'href'?: string;
    /**
     * Id of the instance
     * @type {string}
     * @memberof WorkContactChangeEvent5fca6c96c1c81000142fd03784140113
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof WorkContactChangeEvent5fca6c96c1c81000142fd03784140113
     */
    'descriptor'?: string;
}

