/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8 } from './display-explicit-skill-representation-d6ca778018011000182fa5be1ae901a8';

/**
 * 
 * @export
 * @interface WorkersGetExplicitSkillsResponse
 */
export interface WorkersGetExplicitSkillsResponse {
    /**
     * 
     * @type {Array<DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8>}
     * @memberof WorkersGetExplicitSkillsResponse
     */
    'data'?: Array<DisplayExplicitSkillRepresentationD6ca778018011000182fa5be1ae901a8>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetExplicitSkillsResponse
     */
    'total'?: number;
}

