/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000 } from './external-skill-level-detail1c67ac98c0f310002706be33dcdb0000';

/**
 * 
 * @export
 * @interface WorkersGetExternalSkillLevelResponse
 */
export interface WorkersGetExternalSkillLevelResponse {
    /**
     * 
     * @type {Array<ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000>}
     * @memberof WorkersGetExternalSkillLevelResponse
     */
    'data'?: Array<ExternalSkillLevelDetail1c67ac98c0f310002706be33dcdb0000>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetExternalSkillLevelResponse
     */
    'total'?: number;
}

