/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015 } from './check-in-topics-summary-d81c816de26f10000ef2c5cb2fdd0015';

/**
 * 
 * @export
 * @interface WorkersGetCheckInTopicsResponse
 */
export interface WorkersGetCheckInTopicsResponse {
    /**
     * 
     * @type {Array<CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015>}
     * @memberof WorkersGetCheckInTopicsResponse
     */
    'data'?: Array<CheckInTopicsSummaryD81c816de26f10000ef2c5cb2fdd0015>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetCheckInTopicsResponse
     */
    'total'?: number;
}

