/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkerJobViewFab4a151b24810000e7ff8d0c7f0126dAllOf } from './worker-job-view-fab4a151b24810000e7ff8d0c7f0126d-all-of';

/**
 * 
 * @export
 * @interface WorkerJobViewFab4a151b24810000e7ff8d0c7f0126d
 */
export interface WorkerJobViewFab4a151b24810000e7ff8d0c7f0126d {
    /**
     * Id of the instance
     * @type {string}
     * @memberof WorkerJobViewFab4a151b24810000e7ff8d0c7f0126d
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof WorkerJobViewFab4a151b24810000e7ff8d0c7f0126d
     */
    'descriptor'?: string;
}

