/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8 } from './skill-item-display-definition4b4b7d34b4a21000301eaf52086700d8';

/**
 * 
 * @export
 * @interface WorkersGetSkillItemsResponse
 */
export interface WorkersGetSkillItemsResponse {
    /**
     * 
     * @type {Array<SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8>}
     * @memberof WorkersGetSkillItemsResponse
     */
    'data'?: Array<SkillItemDisplayDefinition4b4b7d34b4a21000301eaf52086700d8>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetSkillItemsResponse
     */
    'total'?: number;
}

