/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JobDataForWorkerB8ac205877fd10000ea91719a02a00a2 } from './job-data-for-worker-b8ac205877fd10000ea91719a02a00a2';
import { Person0ad147648b0a1000237bd486634a001a } from './person0ad147648b0a1000237bd486634a001a';
import { PrimaryJob352c3a97ecd51000353cba144c5b0042 } from './primary-job352c3a97ecd51000353cba144c5b0042';
import { WorkerType3f78eeedc01d1000138d97d80e5a0000 } from './worker-type3f78eeedc01d1000138d97d80e5a0000';

/**
 * 
 * @export
 * @interface WorkerDataC2466b0778c610000d1936006720000eAllOf
 */
export interface WorkerDataC2466b0778c610000d1936006720000eAllOf {
    /**
     * 
     * @type {PrimaryJob352c3a97ecd51000353cba144c5b0042}
     * @memberof WorkerDataC2466b0778c610000d1936006720000eAllOf
     */
    'primaryJob'?: PrimaryJob352c3a97ecd51000353cba144c5b0042;
    /**
     * 
     * @type {Person0ad147648b0a1000237bd486634a001a}
     * @memberof WorkerDataC2466b0778c610000d1936006720000eAllOf
     */
    'person'?: Person0ad147648b0a1000237bd486634a001a;
    /**
     * The Employee ID or Contingent Worker ID for the worker.
     * @type {string}
     * @memberof WorkerDataC2466b0778c610000d1936006720000eAllOf
     */
    'workerId'?: string;
    /**
     * 
     * @type {WorkerType3f78eeedc01d1000138d97d80e5a0000}
     * @memberof WorkerDataC2466b0778c610000d1936006720000eAllOf
     */
    'workerType'?: WorkerType3f78eeedc01d1000138d97d80e5a0000;
    /**
     * The employee’s additional jobs and international assignments.
     * @type {Array<JobDataForWorkerB8ac205877fd10000ea91719a02a00a2>}
     * @memberof WorkerDataC2466b0778c610000d1936006720000eAllOf
     */
    'additionalJobs'?: Array<JobDataForWorkerB8ac205877fd10000ea91719a02a00a2>;
    /**
     * Id of the instance
     * @type {string}
     * @memberof WorkerDataC2466b0778c610000d1936006720000eAllOf
     */
    'id'?: string;
    /**
     * A preview of the instance
     * @type {string}
     * @memberof WorkerDataC2466b0778c610000d1936006720000eAllOf
     */
    'descriptor'?: string;
}

