/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ServiceDatesData6b1db753fd82100027b0c8519c860018 } from './service-dates-data6b1db753fd82100027b0c8519c860018';

/**
 * 
 * @export
 * @interface WorkersGetServiceDatesResponse
 */
export interface WorkersGetServiceDatesResponse {
    /**
     * 
     * @type {Array<ServiceDatesData6b1db753fd82100027b0c8519c860018>}
     * @memberof WorkersGetServiceDatesResponse
     */
    'data'?: Array<ServiceDatesData6b1db753fd82100027b0c8519c860018>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetServiceDatesResponse
     */
    'total'?: number;
}

