/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckInsSummaryB3a69f47a499100010ce6be72bfe001d } from './check-ins-summary-b3a69f47a499100010ce6be72bfe001d';

/**
 * 
 * @export
 * @interface WorkersGetCheckInsResponse
 */
export interface WorkersGetCheckInsResponse {
    /**
     * 
     * @type {Array<CheckInsSummaryB3a69f47a499100010ce6be72bfe001d>}
     * @memberof WorkersGetCheckInsResponse
     */
    'data'?: Array<CheckInsSummaryB3a69f47a499100010ce6be72bfe001d>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetCheckInsResponse
     */
    'total'?: number;
}

