/*
staffing

The Staffing REST APIs enable you to get and manage staffing information, such as jobs, job families, job profiles, supervisory organizations, worker check-ins, and job changes. The Staffing service also includes the /workers resource to access staffing information for non-terminated workers.



Related Information:
- Administrator Guide: Setup Considerations: Job Changes

The version of the OpenAPI document: v6


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WorkerDataC2466b0778c610000d1936006720000e } from './worker-data-c2466b0778c610000d1936006720000e';

/**
 * 
 * @export
 * @interface WorkersGetCollectionStaffingResponse
 */
export interface WorkersGetCollectionStaffingResponse {
    /**
     * 
     * @type {Array<WorkerDataC2466b0778c610000d1936006720000e>}
     * @memberof WorkersGetCollectionStaffingResponse
     */
    'data'?: Array<WorkerDataC2466b0778c610000d1936006720000e>;
    /**
     * 
     * @type {number}
     * @memberof WorkersGetCollectionStaffingResponse
     */
    'total'?: number;
}

